[phases.setup]
nixPkgs = ["jdk11", "maven"]

[phases.build]
cmds = ["cd starrating-backend && mvn clean install -DskipTests"]

[start]
cmd = "java -jar starrating-backend/target/*.jar --server.port=$PORT"
